version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: "neo4j/1234" 
    ports:
      - "7687:7687" 
      - "7474:7474" 
    volumes:
      - neo4j_data:/data

  lake-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_NEO4J_URI: bolt://neo4j:7687
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: 1234
    ports:
      - "8081:8081"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
